server:
  port: 19001

spring:
  application:
    name: consumer
feign:
  hystrix:
    enabled: true

eureka:
  client:
    register-with-eureka: false
    service-url:
          defaultZone:  http://localhost:17001/eureka/
