server:
  port: 17001
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false    # 不注册
    fetch-registry: false          # 不扫描
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  # 注册中心
  server:
    enable-self-preservation: true    # 自我保护机制 默认true 保留暂时失联的服务，随心跳恢复而恢复