server:
  port: 10003

spring:
  application:
    name: tiantianconfig
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pwaydn/cloud-config.git
          search-paths: /**
          default-label: master
          username: pwaydn
          password: a83384132